name: Windows Vulkan Intel Clang

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

jobs:
  Windows-VK-Intel-Clang:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: On
      TestTarget: check-hlsl-clang-vk
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
