name: Windows D3D12 Intel DXC

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # run every 30 minutes

  pull_request:
    branches:
      - main

jobs:
  Windows-D3D12-Intel-DXC:
    uses: ./.github/workflows/test-all.yaml
    with:
      OS: windows
      SKU: GPU-Intel
      Test-Clang: Off
      BuildType: Debug
      TestTarget: check-hlsl-d3d12
      HLSLTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
